apiVersion: v1
kind: Pod
metadata:
  name: burstable-qos-demo
  namespace: qos-example
spec:
  containers:
    - name: burstable-qos-demo-ctr
      image: nginx
      resources:
        limits:
          memory: "200Mi"
        requests:
          memory: "100Mi" # To be burstable, at least one Container in Pod must have a request. And requests must be different to limits, otherwise it would be Guaranteed QoS
