apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo-2
  namespace: cpu-example
spec:
  containers:
    - name: cpu-demo-2-ctr
      image: polinux/stress
      resources:
        requests:
          cpu: "50Mi"
        limits:
          cpu: "100Mi"
      command: ["stress"]
      args: ["--vm","1","--vm-bytes","250M","--vm-hang","1"]